# Generated by Django 4.1.7 on 2025-04-29 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('prize_pool', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('UPCOMING', 'Upcoming'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], max_length=20)),
                ('battle_type', models.CharField(max_length=20)),
                ('max_participants', models.IntegerField()),
                ('rules', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_battles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Battle',
                'verbose_name_plural': 'Battles',
                'db_table': 'battle',
            },
        ),
        migrations.CreateModel(
            name='BattleParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission', models.FileField(null=True, upload_to='battle_submissions/')),
                ('score', models.IntegerField(null=True)),
                ('submission_time', models.DateTimeField(null=True)),
                ('status', models.CharField(max_length=20)),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battle.battle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Battle Participant',
                'verbose_name_plural': 'Battle Participants',
                'db_table': 'battle_participant',
            },
        ),
        migrations.AddField(
            model_name='battle',
            name='participants',
            field=models.ManyToManyField(through='battle.BattleParticipant', to=settings.AUTH_USER_MODEL),
        ),
    ]
